# GitHub Sponsors / Funding configuration for the JobX10 (JX10) project

custom:
  - https://jobx10.com

# Cryptocurrency support
# All addresses are on the Ethereum / Polygon network (EVM-compatible)

ethereum: "0x24e65dcc5ca41251674fe9d36af6ff1ecbb2c02d"
polygon: "0x24e65dcc5ca41251674fe9d36af6ff1ecbb2c02d"
usdt: "0x24e65dcc5ca41251674fe9d36af6ff1ecbb2c02d"
usdc: "0x24e65dcc5ca41251674fe9d36af6ff1ecbb2c02d"

# Optional (currently unused providers)
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
