# GitHub Sponsors / Funding configuration for the JobX10 (JX10) project

# Hauptlink
custom:
  - "https://jobx10.com"
  - "https://polygonscan.com/address/0x24e65dcc5ca41251674fe9d36af6ff1ecbb2c02d"
  - "https://jobx10.com/donate"   # Falls du später eine Spenden-Seite machst


# Optionale Provider (leer lassen oder korrekt ausfüllen)
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
